---

- name: prepare ubuntu golden image
  hosts: linux
  gather_facts: no
  tasks:
    - name: apt update 
      apt:
        update_cache: yes
      become: yes
    - name: apt upgrade 
      apt:
          upgrade: dist
      become: yes
    - name: install packages 
      apt:
          pkg:
                  - build-essential
                  - curl
                  - file
                  - git
                  - zsh
                  - git-core
                  - fonts-powerline
                  - silversearcher-ag
                  - neovim
      become: yes
      tags: apt-install
    - name: install oh my zsh
      shell: 
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    - name: get powerleve10k
      shell:
        cmd: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
    - name: install powerlevel10K
      lineinfile:
              path: ~/.zshrc
              regexp: ^(ZSH_THEME).*
              line: ZSH_THEME="powerlevel10k/powerlevel10k"
      tags: zsh-powerlevel10k
    # run p10k interactive wizard afterwards by starting zsh from bash prompt
    # change the default shell with chsh -s $(which zsh) afterwards.
    - name: get nvim configuration file
      git:
              repo: https://github.com/rinmeister/nvim.git
              dest: /home/ubuntu/.config/nvim
      tags: nvim
    - name: set up alias for nvim
      lineinfile:
              path: /home/ubuntu/.zshrc
              insertafter: ^#\salias\soh.*
              line: alias vi="nvim"
      tags:
              - nvim
              - nvim-config
    # run PlugInstall from neovim afterwards.
